import '../../../shared/models/job_model.dart';

class MockJobs {
  static List<JobModel> get defaultJobs => [
        JobModel(
          id: 'mock_1',
          title: {'ar': 'مطور تطبيقات فلاتر', 'en': 'Flutter Developer'},
          company: 'TechMinds Solutions',
          location: {'ar': 'رام الله، فلسطين', 'en': 'Ramallah, Palestine'},
          postedAt: DateTime.now().subtract(const Duration(days: 1)),
          expiresAt: DateTime.now().add(const Duration(days: 14)),
          description: {
            'ar': 'نبحث عن مطور فلاتر موهوب للانضمام إلى فريقنا المتنامي...',
            'en': 'We are looking for a talented Flutter developer to join our growing team...',
          },
          requirements: {
            'ar': ['خبرة سنة على الأقل', 'معرفة جيدة بتصميم الواجهات', 'التعامل مع APIs'],
            'en': ['At least 1 year of experience', 'Good knowledge of UI design', 'API integration'],
          },
          responsibilities: {
            'ar': ['تطوير الميزات الجديدة: تطبيق خطط العمل', 'صيانة الكود: التأكد من جودة الأداء'],
            'en': ['Develop new features: Implement roadmaps', 'Code maintenance: Ensure performance quality'],
          },
          applyUrl: 'https://example.com/apply/1',
          categoryId: 'it',
          subCategoryId: 'mobile_dev',
          educationLevelId: 'bachelor',
          iconId: 'code_icon',
          jobType: 'full-time',
          level: 'entry',
          skills: ['Flutter', 'Dart', 'Firebase'],
          isActive: true,
        ),
        JobModel(
          id: 'mock_2',
          title: {'ar': 'مطور ويب الواجهة الخلفية', 'en': 'Backend Web Developer'},
          company: 'CloudGate Systems',
          location: {'ar': 'نابلس، فلسطين (عن بُعد)', 'en': 'Nablus, Palestine (Remote)'},
          postedAt: DateTime.now().subtract(const Duration(days: 3)),
          expiresAt: DateTime.now().add(const Duration(days: 10)),
          description: {
            'ar': 'شركة رائدة تبحث عن مطور باك إند متمرس في Node.js.',
            'en': 'A leading company is looking for an experienced Node.js backend developer.',
          },
          requirements: {
            'ar': ['خبرة 3 سنوات', 'إجادة Node.js و MongoDB', 'فهم هندسة Microservices'],
            'en': ['3 years experience', 'Proficiency in Node.js and MongoDB', 'Microservices architecture understanding'],
          },
          responsibilities: {
            'ar': ['تصميم قواعد البيانات', 'إنشاء RESTful APIs', 'تحسين الأداء والحماية'],
            'en': ['Database design', 'Build RESTful APIs', 'Optimize performance and security'],
          },
          applyUrl: 'https://example.com/apply/2',
          categoryId: 'it',
          subCategoryId: 'web_dev',
          educationLevelId: 'bachelor',
          iconId: 'server_icon',
          jobType: 'remote',
          level: 'mid',
          skills: ['Node.js', 'MongoDB', 'Express'],
          isActive: true,
        ),
        JobModel(
          id: 'mock_3',
          title: {'ar': 'مهندس مدني', 'en': 'Civil Engineer'},
          company: 'BuildPro Construction',
          location: {'ar': 'الخليل، فلسطين', 'en': 'Hebron, Palestine'},
          postedAt: DateTime.now().subtract(const Duration(hours: 12)),
          expiresAt: DateTime.now().add(const Duration(days: 20)),
          description: {
            'ar': 'مطلوب مهندس مدني للإشراف على مشاريع إسكان.',
            'en': 'Civil engineer required to supervise housing projects.',
          },
          requirements: {
            'ar': ['بكالوريوس هندسة مدنية', 'رخصة قيادة', 'القدرة على تحمل ضغط العمل'],
            'en': ['BSc Civil Engineering', 'Driving license', 'Ability to work under pressure'],
          },
          responsibilities: {
            'ar': ['الإشراف الميداني', 'إعداد التقارير اليومية', 'التنسيق مع المقاولين'],
            'en': ['Site supervision', 'Prepare daily reports', 'Coordinate with contractors'],
          },
          applyUrl: 'https://example.com/apply/3',
          categoryId: 'engineering',
          subCategoryId: 'civil',
          educationLevelId: 'bachelor',
          iconId: 'construct_icon',
          jobType: 'full-time',
          level: 'mid',
          skills: ['AutoCAD', 'Management'],
          isActive: true,
        ),
        JobModel(
          id: 'mock_4',
          title: {'ar': 'أخصائي تسويق رقمي', 'en': 'Digital Marketing Specialist'},
          company: 'MarketGrowth',
          location: {'ar': 'عن بُعد', 'en': 'Remote'},
          postedAt: DateTime.now().subtract(const Duration(days: 2)),
          expiresAt: DateTime.now().add(const Duration(days: 5)),
          description: {
            'ar': 'هل أنت مبدع في إطلاق الحملات الإعلانية؟ انضم إلينا.',
            'en': 'Are you creative in launching ad campaigns? Join us.',
          },
          requirements: {
            'ar': ['خبرة في إعلانات جوجل وفيسبوك', 'القدرة على تحليل البيانات', 'مهارات كتابة المحتوى'],
            'en': ['Experience in Google & FB Ads', 'Data analysis skills', 'Copywriting skills'],
          },
          responsibilities: {
            'ar': ['إدارة الحملات الإعلانية', 'تحليل العائد على الاستثمار ROI', 'كتابة تقارير الأداء'],
            'en': ['Manage ad campaigns', 'Analyze ROI', 'Write performance reports'],
          },
          applyUrl: 'https://example.com/apply/4',
          categoryId: 'business',
          subCategoryId: 'marketing',
          educationLevelId: 'diploma',
          iconId: 'bullhorn_icon',
          jobType: 'remote',
          level: 'junior',
          skills: ['SEO', 'Google Ads', 'Social Media'],
          isActive: true,
        ),
      ];
}
